# Generated by Django 5.0 on 2024-01-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseGroup',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False, verbose_name='release number')),
                ('name', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('desc', models.TextField(blank=True)),
                ('bc_embed', models.TextField(blank=True)),
                ('bc_link', models.URLField(blank=True)),
                ('spotify_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=45, verbose_name='format')),
                ('date', models.DateField()),
                ('num', models.IntegerField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('count', models.IntegerField(blank=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.releasegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_specific_to_format', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('num', models.IntegerField()),
                ('duration', models.DurationField()),
                ('lyrics', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.release')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.artist')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.detailtype')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.releasegroup')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.track')),
            ],
        ),
    ]
