# Generated by Django 5.0 on 2024-01-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_releasegroup_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='cat_id',
            new_name='release',
        ),
    ]
