# Generated by Django 5.0 on 2024-01-05 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_cat_id_release_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.track'),
        ),
    ]
